#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

ASSETS=$(cd "$(dirname "$0")" && pwd)
source $ASSETS/helpers/utils.sh
source $ASSETS/helpers/bitbucket.sh

# for all temporary files in 'check'
tmpfile() {
  tmp_file "check-$1"
}

# for jq
PATH=/usr/local/bin:$PATH

payload=$(tmpfile request)

cat > $payload <&0

# reset result payload from previous check
result_payload=$(tmpfile result)
echo "[]" > "$result_payload"

include_source() {
  echo "$(jq ". + [$(jq -c '.' <&0)]" < "$result_payload")" > "$result_payload"
}

# scan all configured repository/branch and call include_source for each of them
bitbucket_filter_repos_branches "$payload" "include_source"

jq -n "[ $(version "$result_payload" "$payload") ]" >&3
